name: 'QEMU'  

on:
#  push: 
  watch:
    types: started
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Ready'
        run: |
          sudo apt install qemu -y
          wget https://raw.githubusercontent.com/majianyu2007/WindowsXP-For-OpenVZ-Img/master/windowsxp.qcow2
          chmod 777 windowsxp.qcow2
          md5sum windowsxp.qcow2


      - name: 'Start QEMU'
        run: |
          nohup qemu-system-x86_64 -m 6144 -boot c -hda windowsxp.qcow2 -net nic,model=rtl8139 -net user -soundhw ac97 -vga cirrus -vnc :1 -net user,hostfwd=tcp::3389-:3389 -localtime &

      - name: 'Start Ngrok'
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip
          unzip ngrok-stable-linux-386.zip
          chmod +x ./ngrok
          rm -f .ngrok.log
          ./ngrok authtoken "1jdfcjYxEdKV485VopgVPOBhf06_2bRDq5UfjYHp9PrzgzsST"
          ./ngrok tcp -authtoken=1jdfcjYxEdKV485VopgVPOBhf06_2bRDq5UfjYHp9PrzgzsST 3389 --log ".ngrok.log" &
          cat .ngrok.log

      - name: 'Sleep'
        run: |
          sleep 99999h

          


