name: 'QEMU'  

on:
#  push: 
  watch:
    types: started
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Ready'
        run: |
          sudo apt install qemu -y
          wget --no-check-certificate http://d.nat.ee/win8.1/win8.1-pro-x64-cn.vhd.gz
          sudo chmod 777 win8.1-pro-x64-cn.vhd.gz
          md5sum win8.1-pro-x64-cn.vhd.gz


      - name: 'Start QEMU'
        run: |
          ls
          nohup sudo qemu-system-x86_64 -m 6144 -boot c -hda /home/runner/win8.1-pro-x64-cn.vhd.gz -net nic,model=rtl8139 -net user -soundhw ac97 -vga cirrus -vnc :1 -net user,hostfwd=tcp::3389-:3389 -localtime &

      - name: 'Start Ngrok'
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip
          unzip ngrok-stable-linux-386.zip
          chmod +x ./ngrok
          rm -f .ngrok.log
          ./ngrok authtoken "1jdfcjYxEdKV485VopgVPOBhf06_2bRDq5UfjYHp9PrzgzsST"
          ./ngrok tcp 5901

      - name: 'Sleep'
        run: |
          sleep 9999999h
 
