name: 'QEMU'  

on:
#  push: 
  watch:
    types: started
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Ready'
        run: |
          cd /
          mkdir qemu0
          cd /qemu0
          sudo apt install qemu -y
          wget http://d.nat.ee/win7/win7-ult-sp1-x64-cn.iso
          sudo chmod 777 *
          md5sum *


      - name: 'Start QEMU'
        run: |
          cd /qemu0
          qemu-img create -f qcow2 /qemu0/main.qcow2 10G
          ls
          pwd
          nohup sudo qemu-system-x86_64 -m 6144 -boot c -hda /qemu0/main.qcow2 -cdrom /qemu0/win7-ult-sp1-x64-cn.iso -net nic,model=rtl8139 -net user -soundhw ac97 -vga cirrus -vnc :1 -net user,hostfwd=tcp::3389-:3389 -localtime &

      - name: 'Start Ngrok'
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip
          unzip ngrok-stable-linux-386.zip
          chmod +x ./ngrok
          rm -f .ngrok.log
          ./ngrok authtoken "1jdfcjYxEdKV485VopgVPOBhf06_2bRDq5UfjYHp9PrzgzsST"
          ./ngrok tcp 5901

      - name: 'Sleep'
        run: |
          sleep 9999999h
 
