name: 'QEMU'  

on:
#  push: 
  watch:
    types: started
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - name: 'Ready'
        run: |
          sudo -i
          cd /
          sudo mkdir qemu0
          cd /qemu0
          sudo apt-get update
          sudo apt install qemu -y
          echo QEMU is installed!
          sudo wget http://a.iplc.best/natee/home/winsrv2012r2-data-x64-cn-home.iso
          sudo chmod 777 *
          sudo md5sum *


      - name: 'Start QEMU'
        run: |
          cd /qemu0
          sudo qemu-img create -f qcow2 /qemu0/main.qcow2 10G
          ls
          pwd
          nohup sudo qemu-system-x86_64 -m 6144 -boot c -hda /qemu0/main.qcow2 -cdrom /qemu0/winsrv2012r2-data-x64-cn-home.iso -net nic,model=rtl8139 -net user -soundhw ac97 -vga cirrus -vnc :1 -net user,hostfwd=tcp::3389-:3389 -localtime &

      - name: 'Start Ngrok'
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        run: |
          sudo wget -q https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip
          sudo unzip ngrok-stable-linux-386.zip
          sudo chmod +x ./ngrok
          sudo rm -f .ngrok.log
          sudo ./ngrok authtoken "1jdfcjYxEdKV485VopgVPOBhf06_2bRDq5UfjYHp9PrzgzsST"
          sudo ./ngrok tcp 5901

      - name: 'Sleep'
        run: |
          sleep 9999999h
